const express=require("express")
const server=express()
const bp=require("body-parser")
server.use(bp.json())
const mongoose=require("mongoose")
const cors = require("cors")
server.use(cors())
const contactapp = require("./routes/contactapp")
const authenticate = require("./routes/auth")
const prot = require("./routes/protected")
const ToDo = require("./routes/todor")
mongoose.connect("mongodb://localhost:27017/Sinon").then((res)=>console.log("connected to db")).catch((err)=>console.log("failure"))
server.use("/",contactapp)
server.use("/",authenticate)
server.use("/",prot)
server.use("/",ToDo)
server.listen(3007,()=>console.log("server connected"))
